travis:
  secure:
    BINSTAR_TOKEN: Uf/Khw7qdEI8v1w2wyxHkgVg4D6spZOqqW+JDBdnpJUyYMfzeJeWRwWwtrptB78gDL6ABM6LfK+GtgvRdJDNugTzBFerJ1jfXfSR24g2NA0lh22k0bUiIpsRo8MdZV1WazWiBpVuxqwpwIQAi1EBgW5IthxE5jSJSJG488WPicJuiC65UXRauC6mzmuvVrCOaKAI9r0U/hZQJw3gPUNPzgE6XdxMzQxtIr/5jHu91B4EGZcWMwnuHzddaFkkBwUle0sakNPMWjlwsa8EAn9g0G0MK7kmGdd7+Rp3OmxIDAvcv//dY7F8xPecd/c+4zFN5P/UWjbXeTYe1O4xhVPZy2mWe8ZrniAeS4JCdM6gK6WrxzgeOUv/T2MUIl6Cw7NurnkUfj8DQ/Nor4j0jtIoPsotlOGUhXtfCaoKz9R9unjhwgTNyt+3Jyo2eaotW7tAL1OuzsZhqi/yU5JFLpPkIj/EHLnmBTnp98jxL9GjUJvdNSX/+rBoMwyokCgz94XDaAE3+nWIIWm6NpwCQkY2upVToWra+EwH5DoH536w45/xnYyMeLBetY5n/8Wmj+Ue+wN79ze956A33mRh6sX6TfPk81rXJaoPkgAgcRfvSQOoI8AVJwu1lIorxR2uA5u9TUAwvGKaHvSuMJFHqX0B1vF2x38TQReCx4GRMzZw5fM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
