travis:
  secure:
    BINSTAR_TOKEN: BQ6Q3dbOJr/ReE2cB16Wgo1/2MwcXHnnvxbzizouaSkQNVhcxiYr/e3N+CHFWpAwx14zSYJFJFuNNJrTrYxFYuNh32ZX68QNCwtvnk+dDgGG+UzxW8EaknVvl6YqeYj3hwh5k85aVipUQI+OkH7YHP37//MUdTUDCFs3lKPPZG7ykY0E7e0vhIJLGXl37YRP1k4AXEwkN+kMVH8bqRbTgj7L3mda9ccZZlm3ZdJo8B4iu0/iVns+XQ0zoLh/4RMe0HlQXKI08RP3gaKtZhuGGqfvAFd+6mxWMXklY8jp1jkhrsphMnddR9jWNOi8U1USyXJwKOdm1P1pYY+XUatYFQus2aaA0j8hKFxVsJUe0prqKw3/0e9zn7Ghgqm95bE7t4ygMwXD2dSPcbAnbKl/3v9xENXTqbLGOU1l3t5bGiGtq4VpO1CQ8su8VxovFHXxMFExYxmgyPPHn5xtVlyaoO1MHGXoqSZ+Ja32JS9UsnVJkaW2djcS3Y2xRl0aTPBFz5lIgD9WL1loqOb6qM4z/DMZF9bOLxNu33ZtmnjGFBW0RaPBOvEs1uZSBqH+kd2U7MnCRrFq+eT5TetMmEC0jLJj23htGWAdok13ATXSMMV/Eyz6TXSCaF7Waw/AmjXLBjqxPWL54xXcdX9huglvzIvVcVj3CYtby3mFTUIOWiY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
