appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: cWWrkVxhiVOq73sjRnAFm+MThL9hJCF5ux6cvAHg6U7XOhq6Rj83QsZShg28e5tS6EhCx+lAEBQIeGJhZ4m6hTmSk7LEqsoCippqVXNHlmRMFEApLREqwPGzJzfo6vkukd+ClZlguY+fl+rsLvMEncaQf8ZlEBhcyE0/OSjx61dWTNpFDw3U9B+0Nrow56gZ4zDy4C07oHJ0ytyDKVZa+WziItNWICA3TH58EVulk3lBZBBDz5CmUhHD6CxAZhw4CDpyB7u7iKomkMw80hbgREoyL/AR74h6+JFpNbADO7pti6E01CRZOqY93TlEPAZZXPr/+JKmp//poogSomQhq3Ybov6jK1PlG04AVGLGu/K0TIJn7LSQR/RiUsKelGARaNykv5A/u3GaFNomqlcQuiOah6YDvEEKISdzyhmwSFFGGNTj/sFjDZz5jW1wUrjZadvXcEkAOLyR3X/TcOkGntpjo5JbI5tf+Fr1DDkUYnkbdacDGERfqaeCGOMZH4WdD2w/cvtUgYcOUM665R2hNGV0jdjYHKIsvLxsVZUjaMA5ZEjsNP79fYQ7TP1sXLSmxxy5D394lqB3792piVfAk7DG5J25tqj9HyJo8Q5u3hdKphSqNdgQhzBiJCVxFY/jOO3fHmkYkcYlwKs8i4li/LzsNjy0Zj6eGHA274mG4zQ=}
